### ISSUE TITLE
/plany should parse units from index

### ISSUE THREAD

**Issue by kuskus-39** [dommilosz/ZSEApi#1]
Assigning this to myself

**Comment by kuskus-39** [comment]
Here: https://github.com/dommilosz/ZSEApi/blob/master/src/getPlany.ts#L22

**Comment by dommilosz** [comment]
It should fetch only one timetable at a time, not iterating over all of them so /api/plany/o22 for example

**Comment by dommilosz** [comment]
Or /plany/oddzial/22

**Comment by kuskus-39** [comment]
That means parsing /index is unnecessary, closing this.
